### ISSUE TITLE
auto-restart option

### ISSUE THREAD

**Issue by thanhson1085** [BuildOnViction/tmn#49]
In some unexpected cases, the node will be shutdown, e.g:
```
ERROR[02-02|02:50:42] Error when update masternodes set. Stopping node err="abi: unmarshalling empty output"
```
Should we provide auto-restart option for `tmn`?, so the node can get back quickly after stopping

**Comment by etienne-napoleone** [comment]
It's unfortunately not really possible with vanilla docker. Or only if over engineering the whole thing (making tmn start a custom deamon that will check the container status ... way too complicated).

I'll release a first version of `create-tomochain-masternode` this week so everybody can use a docker-compose setup with the auto restart enabled.

What do you think?

**Comment by thanhson1085** [comment]
It is OK.

We should have some product guide line for `create-tomochain-masternode` in the docs site.

**Comment by etienne-napoleone** [comment]
Yes I will add them before releasing!
